import assert from "node:assert/strict";
import test from "node:test";

import { seedJavaJob } from "../src/stacks/java/scenarios/seeds.ts";

test("Java order-service deep link opens at the real analysis_review boundary", () => {
  const job = seedJavaJob("java-order-service");
  assert.equal(job.currentStage, 1);
  assert.equal(job.currentPhase, "ANALYSIS_AGENT");
  assert.equal(job.currentGate, "analysis_review");
  assert.equal(job.phaseGates.at(-1)?.type, "analysis_review");
});

test("Java repair deep link is generated by the real Stage 2 failure path", () => {
  const job = seedJavaJob("java-repair-service");
  assert.equal(job.currentStage, 2);
  assert.equal(job.currentPhase, "REPAIR_FAILURE");
  assert.equal(job.currentGate, "repair_review");
  assert.equal(job.repair.attempts.length, 1);
  assert.equal(job.repair.attempts[0]?.status, "REVIEWED");
});

test("Java terminal deep link is a completed Stage 4 report state with zero open gates", () => {
  const job = seedJavaJob("java-terminal-service");
  assert.equal(job.currentStage, 4);
  assert.equal(job.currentGate, null);
  assert.equal(job.terminalStage4.acceptedOutputRevision, 1);
  assert.equal(job.finalReport.status, "GENERATED");
  assert.equal(job.status, "COMPLETED");
  assert.equal(job.phaseGates.some((gate) => gate.status === "PENDING"), false);
});
