export const ANGULAR11_CRUD_SOURCE = {
  repository: "cornflourblue/angular-11-crud-example",
  revision: "eda3cf6278c02e4fb65f91ec73a9281d4325514e",
  applicationName: "angular-crud-example",
  sourcePath: "/workspace/angular-11-crud-example",
  angular: "11.0.4",
  angularCli: "11.0.4",
  buildAngular: "0.1100.4",
  typescript: "4.0.2",
  rxjs: "6.6.x",
  zoneJs: "0.10.x",
  projects: 1,
  lazyFeatureModules: 1,
  crudOperations: 5,
  packageEntries: 28,
  thirdPartyEntries: 17,
  builder: "@angular-devkit/build-angular:browser",
  lockfile: "package-lock.json",
  routes: ["/", "/users", "/users/add", "/users/edit/:id"],
  architecture: [
    "NgModule application architecture",
    "Lazy-loaded UsersModule",
    "Reactive Forms",
    "HttpClient service layer",
    "HTTP interceptor chain",
    "localStorage-backed development API interceptor",
  ],
  tooling: {
    unit: "Karma 5.1 + Jasmine 3.6 + Chrome launcher",
    lint: "TSLint 6.1 + Codelyzer 6",
    e2e: "Protractor 7 + Jasmine",
  },
} as const;
